#!/usr/bin/env python3
"""
Sync root .env to sub-project config files.

Reads the single-source-of-truth .env at the project root and generates:
  - mobile_app/.env         (copy for Flutter — assets can't reference parent dirs)
  - admin-dashboard/.env    (VITE_ prefixed variables for Vite)
  - jetson/config/config.json  (supabase credentials in sync block)

Usage:
    python sync_env.py

If .env is missing, automatically copies from .env.development (committed to repo).
The root .env is NEVER modified (read-only source of truth).
Flutter reads mobile_app/.env via flutter_dotenv (local dev); CI uses --dart-define.
This script has zero external dependencies (stdlib only).
"""

import json
import os
import sys

ROOT = os.path.dirname(os.path.abspath(__file__))


def parse_env(path):
    """Parse KEY=VALUE lines from .env file, skip comments and blanks."""
    env = {}
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if "=" in line:
                key, _, value = line.partition("=")
                env[key.strip()] = value.strip()
    return env


def sync_admin_dashboard(env):
    """Write admin-dashboard/.env with VITE_ prefixed Supabase vars."""
    out_path = os.path.join(ROOT, "admin-dashboard", ".env")
    def _quote(v):
        v = v.strip('"').strip("'")
        if any(c in v for c in (' ', '$', '`', '"', '\\', '#', '!')):
            return f'"{v}"'
        return v

    lines = [
        "# Auto-generated by sync_env.py — do not edit manually.",
        "# Source: root .env",
        f"VITE_SUPABASE_URL={_quote(env.get('SUPABASE_URL', ''))}",
        f"VITE_SUPABASE_ANON_KEY={_quote(env.get('SUPABASE_ANON_KEY', ''))}",
        f"VITE_SENTRY_DSN={_quote(env.get('SENTRY_DSN', ''))}",
        "",
    ]
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"  [OK] admin-dashboard/.env")


def sync_jetson_config(env):
    """Inject Supabase credentials into jetson/config/config.json."""
    cfg_path = os.path.join(ROOT, "jetson", "config", "config.json")
    if not os.path.exists(cfg_path):
        print(f"  [SKIP] {cfg_path} not found")
        return

    with open(cfg_path, "r", encoding="utf-8") as f:
        config = json.load(f)

    config.setdefault("sync", {})
    config["sync"]["supabase_url"] = env.get("SUPABASE_URL", "")
    config["sync"]["supabase_key"] = env.get("SUPABASE_ANON_KEY", "")

    with open(cfg_path, "w", encoding="utf-8") as f:
        json.dump(config, f, indent=4)
        f.write("\n")
    print(f"  [OK] jetson/config/config.json")


MOBILE_KEYS = {"SUPABASE_URL", "SUPABASE_ANON_KEY", "GOOGLE_WEB_CLIENT_ID", "SENTRY_DSN"}


def sync_mobile_app(env):
    """Write mobile_app/.env with only the keys the Flutter app needs.

    Intentionally excludes SUPABASE_SERVICE_ROLE_KEY and GOOGLE_APPLICATION_CREDENTIALS_DATA
    so they are never bundled into local debug APK builds.
    """
    dest = os.path.join(ROOT, "mobile_app", ".env")
    lines = [
        "# Auto-generated by sync_env.py — do not edit manually.",
        "# Source: root .env (filtered to mobile-safe keys only)",
    ]
    for key in sorted(MOBILE_KEYS):
        if key in env:
            val = env[key].strip('"').strip("'")
            # Quote values that contain shell-unsafe characters
            if any(c in val for c in (' ', '$', '`', '"', '\\', '#', '!')):
                lines.append(f'{key}="{val}"')
            else:
                lines.append(f"{key}={val}")
    lines.append("")
    with open(dest, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print("  [OK] mobile_app/.env")


def main():
    env_path = os.path.join(ROOT, ".env")
    dev_path = os.path.join(ROOT, ".env.development")

    if not os.path.exists(env_path):
        if os.path.exists(dev_path):
            print("[INFO] .env not found — copying from .env.development")
            import shutil
            shutil.copy2(dev_path, env_path)
        else:
            print("[ERROR] Root .env not found.")
            print("  Copy .env.development to .env first:")
            print("    cp .env.development .env")
            sys.exit(1)

    env = parse_env(env_path)
    print(f"Loaded {len(env)} variables from .env")
    print("Syncing to sub-projects:")

    sync_mobile_app(env)
    sync_admin_dashboard(env)
    sync_jetson_config(env)

    print("\nDone! Sub-project configs synced from root .env.")


if __name__ == "__main__":
    main()
