"""
AgriKD - ONNX to TFLite Conversion Script
==========================================
Converts an ONNX model to TensorFlow Lite (.tflite) format.
Uses onnx2tf Python API (not CLI) to ensure correct venv Python is used.

Usage (config-driven):
    python convert_onnx_to_tflite.py --config ../configs/tomato.json

Usage (CLI args):
    python convert_onnx_to_tflite.py \
        --input ../../models/tomato/tomato_student.onnx \
        --output ../../models/tomato/tomato_student.tflite
"""

import argparse
import os
import sys
import shutil
import glob
import time

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from model_definition import load_leaf_config


def convert_onnx_to_tflite(input_path, output_path, quantize="none"):
    print(f"\n{'='*60}")
    print(f"  AgriKD: ONNX -> TFLite Conversion")
    print(f"{'='*60}")

    if not os.path.exists(input_path):
        raise FileNotFoundError(f"Input ONNX model not found: {input_path}")

    output_dir = os.path.dirname(output_path) or '.'
    os.makedirs(output_dir, exist_ok=True)
    temp_dir = os.path.join(output_dir, f"temp_onnx2tf_{int(time.time())}")
    os.makedirs(temp_dir, exist_ok=True)

    print(f"[...] Converting ONNX -> TFLite using onnx2tf Python API...")

    try:
        import onnx2tf
        onnx2tf.convert(
            input_onnx_file_path=input_path,
            output_folder_path=temp_dir,
            non_verbose=True,
        )
    except Exception as e:
        print(f"[!] onnx2tf Python API failed: {e}")
        print("[...] Falling back to subprocess with venv Python...")

        import subprocess
        cmd = [
            sys.executable, "-m", "onnx2tf",
            "-i", input_path,
            "-o", temp_dir,
        ]
        result = subprocess.run(cmd, capture_output=True, text=True)
        if result.returncode != 0:
            print(f"[!] onnx2tf subprocess also failed:\n{result.stderr[-500:]}")
            shutil.rmtree(temp_dir, ignore_errors=True)
            return

    # onnx2tf creates the tflite file inside the output directory
    generated_tflite = os.path.join(temp_dir, "model_float32.tflite")
    if not os.path.exists(generated_tflite):
        files = glob.glob(os.path.join(temp_dir, "*.tflite"))
        if files:
            generated_tflite = files[0]
        else:
            print("[!] Could not find any .tflite files generated by onnx2tf.")
            shutil.rmtree(temp_dir, ignore_errors=True)
            return

    # Move to the requested output path
    shutil.move(generated_tflite, output_path)

    # Clean up temp dir
    shutil.rmtree(temp_dir, ignore_errors=True)

    print(f"[OK] TFLite model generated: {output_path}")

    in_size = os.path.getsize(input_path) / (1024 * 1024)
    out_size = os.path.getsize(output_path) / (1024 * 1024)
    compression = (1 - (out_size / in_size)) * 100
    print(f"    ONNX size:   {in_size:.2f} MB")
    print(f"    TFLite size: {out_size:.2f} MB")
    print(f"    Compression: {compression:.1f}%")
    print(f"{'='*60}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Convert ONNX model to TFLite format.")
    parser.add_argument("--config", type=str, default=None, help="Path to leaf config JSON (auto-fills input/output)")
    parser.add_argument("--input", type=str, default=None, help="Path to input .onnx file")
    parser.add_argument("--output", type=str, default=None, help="Path to output .tflite file")
    parser.add_argument("--quantize", type=str, choices=["none", "float16", "dynamic"], default="none",
                        help="Quantization type (default: none)")

    args = parser.parse_args()

    if args.config:
        cfg = load_leaf_config(args.config)
        if args.input is None:
            args.input = cfg["_paths"]["onnx"]
        if args.output is None:
            args.output = cfg["_paths"]["tflite"]

    if not args.input or not args.output:
        parser.error("Either --config or both --input and --output are required")

    convert_onnx_to_tflite(args.input, args.output, args.quantize)
