"""
AgriKD - ONNX to TFLite Conversion Script
==========================================
Converts an ONNX model to TensorFlow Lite (.tflite) format.
Uses onnx2tf Python API (not CLI) to ensure correct venv Python is used.
Generates BOTH float16 and float32 TFLite variants.

Usage (config-driven):
    python convert_onnx_to_tflite.py --config ../configs/tomato.json

Usage (CLI args):
    python convert_onnx_to_tflite.py \
        --input ../../models/tomato/tomato_student.onnx \
        --output ../../models/tomato/tomato_student.tflite
"""

import argparse
import logging
import os
import sys
import shutil
import glob
import time

logger = logging.getLogger(__name__)

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from model_definition import load_leaf_config


def convert_onnx_to_tflite(input_path, output_path):
    logger.info(f"\n{'='*60}")
    logger.info(f"  AgriKD: ONNX -> TFLite Conversion")
    logger.info(f"{'='*60}")

    if not os.path.exists(input_path):
        raise FileNotFoundError(f"Input ONNX model not found: {input_path}")

    output_dir = os.path.dirname(output_path) or '.'
    os.makedirs(output_dir, exist_ok=True)
    temp_dir = os.path.join(output_dir, f"temp_onnx2tf_{int(time.time())}")
    os.makedirs(temp_dir, exist_ok=True)

    logger.info(f"[...] Converting ONNX -> TFLite using onnx2tf Python API...")

    try:
        import onnx2tf
        onnx2tf.convert(
            input_onnx_file_path=input_path,
            output_folder_path=temp_dir,
            non_verbose=True,
        )
    except Exception as e:
        logger.warning(f"[!] onnx2tf Python API failed: {e}")
        logger.warning("[...] Falling back to subprocess with venv Python...")

        import subprocess
        cmd = [
            sys.executable, "-m", "onnx2tf",
            "-i", input_path,
            "-o", temp_dir,
        ]
        result = subprocess.run(cmd, capture_output=True, text=True)
        if result.returncode != 0:
            logger.error(f"[!] onnx2tf subprocess also failed:\n{result.stderr[-500:]}")
            shutil.rmtree(temp_dir, ignore_errors=True)
            raise RuntimeError(
                f"onnx2tf conversion failed:\n{result.stderr[-500:]}"
            )

    # onnx2tf generates both *_float16.tflite (~0.95 MB) and *_float32.tflite (~1.87 MB).
    tflite_files = glob.glob(os.path.join(temp_dir, "*.tflite"))
    if not tflite_files:
        logger.error("[!] Could not find any .tflite files generated by onnx2tf.")
        shutil.rmtree(temp_dir, ignore_errors=True)
        raise RuntimeError("No .tflite files generated by onnx2tf.")

    logger.info(f"    Generated TFLite files:")
    for f in sorted(tflite_files):
        logger.info(f"      {os.path.basename(f)}: {os.path.getsize(f) / (1024*1024):.2f} MB")

    # Derive base name from output_path: e.g. "tomato_student"
    base_name = os.path.basename(output_path).replace('.tflite', '')

    float16_files = [f for f in tflite_files if "float16" in os.path.basename(f)]
    float32_files = [f for f in tflite_files if "float32" in os.path.basename(f)]

    result_paths = {}
    in_size = os.path.getsize(input_path) / (1024 * 1024)

    for variant, src_list in [("float16", float16_files), ("float32", float32_files)]:
        if src_list:
            dest = os.path.join(output_dir, f"{base_name}_{variant}.tflite")
            shutil.move(src_list[0], dest)
            result_paths[variant] = dest
            out_size = os.path.getsize(dest) / (1024 * 1024)
            compression = (1 - (out_size / in_size)) * 100
            logger.info(f"    {variant}: {out_size:.2f} MB ({compression:.1f}% compression)")

    # Backward compat: copy float16 to the original output_path (e.g. tomato_student.tflite)
    if "float16" in result_paths:
        shutil.copy2(result_paths["float16"], output_path)
    elif "float32" in result_paths:
        shutil.copy2(result_paths["float32"], output_path)

    # Validate generated TFLite files
    for variant, tflite_path in result_paths.items():
        fsize = os.path.getsize(tflite_path)
        if fsize < 1024:
            raise RuntimeError(f"TFLite {variant} too small ({fsize} bytes) — likely corrupt: {tflite_path}")
        try:
            from ai_edge_litert.interpreter import Interpreter
            interp = Interpreter(model_path=tflite_path)
            interp.allocate_tensors()
            logger.info(f"    [OK] {variant} validated ({fsize / (1024*1024):.2f} MB, loadable)")
        except ImportError:
            logger.warning(f"    [WARN] {variant} size OK ({fsize / (1024*1024):.2f} MB) but load test skipped — ai_edge_litert not installed")
        except Exception as e:
            raise RuntimeError(f"TFLite {variant} failed load test: {e}")

    # Clean up temp dir
    shutil.rmtree(temp_dir, ignore_errors=True)

    logger.info(f"\n[OK] TFLite models generated:")
    for variant, path in result_paths.items():
        logger.info(f"    {variant}: {path}")
    logger.info(f"    compat:  {output_path}")
    logger.info(f"{'='*60}")

    return result_paths


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Convert ONNX model to TFLite format.")
    parser.add_argument("--config", type=str, default=None, help="Path to leaf config JSON (auto-fills input/output)")
    parser.add_argument("--input", type=str, default=None, help="Path to input .onnx file")
    parser.add_argument("--output", type=str, default=None, help="Path to output .tflite file")

    args = parser.parse_args()

    if args.config:
        cfg = load_leaf_config(args.config)
        if args.input is None:
            args.input = cfg["_paths"]["onnx"]
        if args.output is None:
            args.output = cfg["_paths"]["tflite"]

    if not args.input or not args.output:
        parser.error("Either --config or both --input and --output are required")

    convert_onnx_to_tflite(args.input, args.output)
