-- =============================================================================
-- AgriKD — 001: Table Definitions
-- =============================================================================
-- Source of truth: admin-dashboard/supabase-schema.sql
-- Cross-validated with: mobile_app (Flutter), jetson (Edge), mlops_pipeline
-- Run in Supabase SQL Editor. Safe to re-run: uses IF NOT EXISTS.
-- =============================================================================

-- ── profiles (extended from auth.users) ─────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.profiles (
    id          UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    email       TEXT UNIQUE,
    role        TEXT DEFAULT 'user' CHECK (role IN ('user', 'admin')),
    is_active   BOOLEAN DEFAULT true,
    created_at  TIMESTAMPTZ DEFAULT now()
);

-- ── predictions ─────────────────────────────────────────────────────────────
-- Flutter inserts via supabase_sync_service.dart; Dashboard reads for analytics.
-- BIGINT id auto-generated; user_id from auth; local_id for sync dedup.
CREATE TABLE IF NOT EXISTS public.predictions (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id               UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    leaf_type             TEXT NOT NULL,
    predicted_class_name  TEXT NOT NULL,
    predicted_class_index INTEGER,
    confidence            REAL NOT NULL,
    all_confidences       JSONB,
    inference_time_ms     FLOAT,
    model_version         TEXT,
    image_url             TEXT,
    notes                 TEXT,
    source                TEXT,
    created_at            TIMESTAMPTZ DEFAULT now(),
    local_id              INTEGER
);

-- ── model_registry ──────────────────────────────────────────────────────────
-- Dashboard writes model_url (float16) + model_url_float32.
-- sync_model_urls() trigger routes file_url based on active_tflite_variant.
-- Flutter reads file_url + sha256_checksum for OTA download + integrity check.
CREATE TABLE IF NOT EXISTS public.model_registry (
    id                    UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    leaf_type             TEXT NOT NULL UNIQUE,
    display_name          TEXT,
    version               TEXT NOT NULL,
    model_url             TEXT,
    model_url_float32     TEXT,
    file_url              TEXT,
    sha256_checksum       TEXT,
    sha256_float32        TEXT,
    active_tflite_variant TEXT DEFAULT 'float16',
    description           TEXT,
    is_active             BOOLEAN DEFAULT true,
    accuracy_top1         FLOAT,
    num_classes           INTEGER,
    class_labels          JSONB,
    created_at            TIMESTAMPTZ DEFAULT now(),
    updated_at            TIMESTAMPTZ
);

-- ── audit_log ───────────────────────────────────────────────────────────────
-- Admin Dashboard logs all CRUD actions here.
CREATE TABLE IF NOT EXISTS public.audit_log (
    id          UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id     UUID REFERENCES auth.users(id),
    action      TEXT NOT NULL,
    entity_type TEXT,
    entity_id   TEXT,
    details     JSONB,
    created_at  TIMESTAMPTZ DEFAULT now()
);

-- ── model_benchmarks ────────────────────────────────────────────────────────
-- Full evaluation results from mlops_pipeline/scripts/evaluate_models.py.
-- 20 columns including per-class metrics, confusion matrix, latency, etc.
CREATE TABLE IF NOT EXISTS public.model_benchmarks (
    id                UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    leaf_type         TEXT NOT NULL,
    version           TEXT NOT NULL,
    format            TEXT NOT NULL CHECK (format IN ('pytorch', 'onnx', 'tflite_float16', 'tflite_float32')),
    accuracy          FLOAT,
    precision_macro   FLOAT,
    recall_macro      FLOAT,
    f1_macro          FLOAT,
    per_class_metrics JSONB,
    confusion_matrix  JSONB,
    latency_mean_ms   FLOAT,
    latency_p99_ms    FLOAT,
    fps               FLOAT,
    size_mb           FLOAT,
    flops_m           FLOAT,
    params_m          FLOAT,
    memory_mb         FLOAT,
    kl_divergence     FLOAT,
    is_candidate      BOOLEAN DEFAULT false,
    created_at        TIMESTAMPTZ DEFAULT now(),
    UNIQUE(leaf_type, version, format)
);

-- ── model_versions ──────────────────────────────────────────────────────────
-- Version archive: Dashboard writes when model is promoted or superseded.
CREATE TABLE IF NOT EXISTS public.model_versions (
    id              UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    leaf_type       TEXT NOT NULL,
    version         TEXT NOT NULL,
    display_name    TEXT,
    model_url       TEXT,
    sha256_checksum TEXT,
    accuracy        FLOAT,
    size_mb         FLOAT,
    archived_at     TIMESTAMPTZ DEFAULT now(),
    UNIQUE(leaf_type, version)
);
