-- ============================================================
-- Migration 012: Device Management + Provisioning Tokens
-- Zero-Touch Provisioning + Admin-Led Asset Management
-- ============================================================

-- 1. Provisioning tokens (Admin creates, Jetson claims once)
CREATE TABLE IF NOT EXISTS public.provisioning_tokens (
    id            TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
    created_by    UUID NOT NULL REFERENCES auth.users(id),
    expires_at    TIMESTAMPTZ NOT NULL DEFAULT (now() + interval '24 hours'),
    used_at       TIMESTAMPTZ,
    used_by_hw_id TEXT,
    device_id     BIGINT,
    label         TEXT,
    created_at    TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE public.provisioning_tokens ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Admin manage tokens" ON public.provisioning_tokens;
CREATE POLICY "Admin manage tokens" ON public.provisioning_tokens
    FOR ALL USING (public.is_admin_role());

DROP POLICY IF EXISTS "Anon read unused tokens" ON public.provisioning_tokens;
CREATE POLICY "Anon read unused tokens" ON public.provisioning_tokens
    FOR SELECT USING (
        id::text = current_setting('request.header.x-provisioning-token-id', true)
        AND used_at IS NULL
        AND expires_at > now()
    );

DROP POLICY IF EXISTS "Anon claim token" ON public.provisioning_tokens;
CREATE POLICY "Anon claim token" ON public.provisioning_tokens
    FOR UPDATE USING (used_at IS NULL AND expires_at > now())
    WITH CHECK (used_at IS NOT NULL);

-- Atomic token claim function — prevents race condition where two devices
-- claim the same token concurrently. Uses SELECT ... FOR UPDATE SKIP LOCKED
-- to ensure only one transaction can lock a given token row.
CREATE OR REPLACE FUNCTION public.claim_provisioning_token(
    p_token_id TEXT,
    p_hw_id TEXT
)
RETURNS TABLE(device_token UUID, device_id BIGINT)
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_catalog AS $$
DECLARE
    v_token_row public.provisioning_tokens%ROWTYPE;
    v_device_id BIGINT;
    v_device_token UUID;
BEGIN
    -- Lock the token row atomically; SKIP LOCKED means a concurrent caller
    -- gets zero rows instead of blocking, so it fails fast.
    SELECT * INTO v_token_row
    FROM public.provisioning_tokens
    WHERE id = p_token_id
      AND used_at IS NULL
      AND expires_at > now()
    FOR UPDATE SKIP LOCKED;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Token not found, already claimed, or expired';
    END IF;

    -- Mark token as used
    UPDATE public.provisioning_tokens
    SET used_at = now(), used_by_hw_id = p_hw_id
    WHERE id = p_token_id;

    RETURN QUERY SELECT d.device_token, d.id
    FROM public.devices d WHERE d.hw_id = p_hw_id LIMIT 1;
END;
$$;

-- 2. Devices table (Admin-Led Asset Management + Device Shadow)
CREATE TABLE IF NOT EXISTS public.devices (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hw_id            TEXT NOT NULL UNIQUE,
    hostname         TEXT NOT NULL DEFAULT 'unknown',
    device_name      TEXT,
    device_type      TEXT NOT NULL DEFAULT 'jetson'
                     CHECK (device_type IN ('jetson', 'camera', 'other')),
    status           TEXT NOT NULL DEFAULT 'unassigned'
                     CHECK (status IN ('unassigned', 'assigned', 'online', 'offline', 'decommissioned')),
    user_id          UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    device_token     UUID UNIQUE DEFAULT gen_random_uuid(),
    desired_config   JSONB NOT NULL DEFAULT '{
        "mode": "manual",
        "interval_seconds": 86400,
        "default_leaf_type": "tomato"
    }'::jsonb,
    reported_config  JSONB,
    config_version   INTEGER NOT NULL DEFAULT 0,
    last_seen_at     TIMESTAMPTZ,
    hw_info          JSONB,
    created_at       TIMESTAMPTZ DEFAULT now()
);

-- FK from provisioning_tokens to devices (deferred to avoid ordering issues)
ALTER TABLE public.provisioning_tokens
    ADD CONSTRAINT fk_prov_device FOREIGN KEY (device_id)
    REFERENCES public.devices(id) ON DELETE SET NULL;

-- 3. Link predictions to device (nullable, backward-compatible)
ALTER TABLE public.predictions
    ADD COLUMN IF NOT EXISTS device_id BIGINT
    REFERENCES public.devices(id) ON DELETE SET NULL;

-- 4. RLS Policies for devices
ALTER TABLE public.devices ENABLE ROW LEVEL SECURITY;

-- Admin: full CRUD on all devices
DROP POLICY IF EXISTS "Admin manage all devices" ON public.devices;
CREATE POLICY "Admin manage all devices" ON public.devices
    FOR ALL USING (public.is_admin_role());

-- User: read own assigned devices
DROP POLICY IF EXISTS "Users read own devices" ON public.devices;
CREATE POLICY "Users read own devices" ON public.devices
    FOR SELECT USING (user_id = auth.uid());

-- User: update ONLY desired_config and device_name on own devices
-- (column-restricted via SECURITY DEFINER function to prevent mutation
-- of hw_id, device_token, status, user_id, etc.)
DROP POLICY IF EXISTS "Users update own device config" ON public.devices;
CREATE POLICY "Users update own device config" ON public.devices
    FOR UPDATE USING (user_id = auth.uid())
    WITH CHECK (user_id = auth.uid());

CREATE OR REPLACE FUNCTION public.update_device_config(
    p_device_id BIGINT,
    p_desired_config JSONB DEFAULT NULL,
    p_device_name TEXT DEFAULT NULL
)
RETURNS void
LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
    UPDATE public.devices
    SET desired_config = COALESCE(p_desired_config, desired_config),
        device_name = COALESCE(p_device_name, device_name)
    WHERE id = p_device_id AND user_id = auth.uid();
    IF NOT FOUND THEN
        RAISE EXCEPTION 'Device not found or not owned by current user';
    END IF;
END;
$$;

-- Device: read own record via X-Device-Token header
DROP POLICY IF EXISTS "Device self-read" ON public.devices;
CREATE POLICY "Device self-read" ON public.devices
    FOR SELECT USING (
        device_token::text = current_setting('request.header.x-device-token', true)
    );

-- Device: update own reported_config + heartbeat
DROP POLICY IF EXISTS "Device update reported" ON public.devices;
CREATE POLICY "Device update reported" ON public.devices
    FOR UPDATE USING (
        device_token::text = current_setting('request.header.x-device-token', true)
    ) WITH CHECK (
        device_token::text = current_setting('request.header.x-device-token', true)
    );

-- Device: self-register (provision.py inserts with anon key)
DROP POLICY IF EXISTS "Device self-register" ON public.devices;
CREATE POLICY "Device self-register" ON public.devices
    FOR INSERT WITH CHECK (status = 'unassigned' AND user_id IS NULL);

-- Device: insert predictions linked to assigned user
DROP POLICY IF EXISTS "Device insert predictions" ON public.predictions;
CREATE POLICY "Device insert predictions" ON public.predictions
    FOR INSERT WITH CHECK (
        EXISTS (
            SELECT 1 FROM public.devices
            WHERE device_token::text = current_setting('request.header.x-device-token', true)
            AND user_id = predictions.user_id
        )
    );

-- 5. Indexes
CREATE INDEX IF NOT EXISTS idx_devices_hw_id ON public.devices(hw_id);
CREATE INDEX IF NOT EXISTS idx_devices_token ON public.devices(device_token);
CREATE INDEX IF NOT EXISTS idx_devices_user ON public.devices(user_id) WHERE user_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_devices_status ON public.devices(status);
CREATE INDEX IF NOT EXISTS idx_predictions_device ON public.predictions(device_id) WHERE device_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_prov_tokens_unused ON public.provisioning_tokens(id) WHERE used_at IS NULL;

-- 6. Auto-increment config_version on desired_config change
CREATE OR REPLACE FUNCTION public.increment_config_version()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.desired_config IS DISTINCT FROM OLD.desired_config THEN
        NEW.config_version := OLD.config_version + 1;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_config_version ON public.devices;
CREATE TRIGGER trg_config_version
    BEFORE UPDATE ON public.devices
    FOR EACH ROW EXECUTE FUNCTION public.increment_config_version();
