name: DVC Push
on:
  workflow_dispatch:

jobs:
  dvc-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install DVC
        run: pip install dvc dvc-gdrive

      - name: DVC Push
        run: |
          dvc remote modify gdrive gdrive_use_service_account true
          dvc push -v
        env:
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
